name: Highlands Green
favicon: null
layout_spectrum: 0.9839798
typography_spectrum: 0.9323308
title: Highlands Green - Nature's Superfoods
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-80284530-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFE'
    - '#777776'
    - '#144029'
    - '#54A946'
    - '#C8C8C7'
  brandStrength: 0.7689713
  lightness: 0.6045531
  saturation: 1
  rhythmicContrast: 0.8490725
purpose: []
