name: Highlands Green
favicon: null
layout_spectrum: 0.23025
typography_spectrum: 0.9323308
title: Highlands Green - Nature's Superfoods
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-80284530-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f18c34'
    - '#897c87'
    - '#44b350'
    - '#b3aab1'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
