name: Highlands Green
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9323308
title: Simply and Naturally
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-80284530-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1A2550'
    - '#C7C2BC'
    - '#5B6990'
    - '#394871'
    - '#868791'
  brandStrength: 0.2472609025426209
  lightness: 0.3972431
  saturation: 0.8619807
  rhythmicContrast: 0.7915717
purpose: []
